### ISSUE TITLE
Piecewise model confidence intervals

### ISSUE THREAD

**Issue by neilstats** [amymariemason/SUMnlmr#21]
In piecewise_summ_figure(), the confidence intervals appear to be calculated using the confidence limits of the LACE estimates (https://github.com/amymariemason/SUMnlmr/blob/main/R/piecewise_new.R#L332). Could you explain why this is used rather than calculating standard errors from the LACE standard errors? [E.g. Consider this simple example with two strata: [https://gist.github.com/neilstats/44ffbb84e5beab7c9f0ad4b0c545d838](https://gist.github.com/neilstats/44ffbb84e5beab7c9f0ad4b0c545d838)]

Also, more generally, this package gives the option of model or bootstrap standard errors. The nlmr package (https://github.com/jrs95/nlmr) also bootstraps the outcome-instrument association and fits piecewise-linear to each, and related NLMR papers all seem to use bootstrap SEs. Is there a reason to use bootstrap SEs, rather than the model-based SEs of the LACE estimates?

Many thanks for your work, and any guidance you can give.

**Comment by amymariemason** [comment]
Re: CI widths
It's worth noting this is only a display choice with regards to the figure drawing - it doesn't impact the linearity tests.  My choices here may not be the best solution and I'm very open to suggestions of improvement.  

The package figure drawing hardsets a chosen reference point arbitrarily at zero. My priority was trying to illustrate much difference there could be from that point, thinking about whether the CI still cross zero or if we see evidence of moving higher/lower.  As each estimate is a local comparison, I was thinking about how the errors could accumulate as we move further out from the reference point. Using the LACE Beta/SEs and chaining them together we are implicitly assuming the point estimate from the first step was correct and losing the uncertainty from the strata in between. E.g. imagine we are going to move two strata to the left and calculate a CI for that compared to the reference point, but that the first strata has a huge SE and the second has a very tight SE - I wanted to quantify the uncertainty of that first step also within the second one i.e. even if the true value of first strata is really at the bottom of its CI, is the next step precise enough to still force it away from the null assumption. This is going to give wider CIs obviously, but I think just fitting the SE would give too tight ones. 


The nlmr package is reliant on having the individual data for drawing up it's confidence intervals, so can bootstrap using that data. The purpose of this package was to separate out the stages so that researchers could share stratified summary data and fit models to stratified summary data - sadly once that is done it is not possible to bootstrap the CIs in the same way and is a weakness of this method. If you have individual-level data, bootstrapping CI directly to get SEs seems preferable to me.

**Comment by amymariemason** [comment]
Re: Bootstrapping

The nlmr package is reliant on having the individual data for drawing up it's confidence intervals, so can bootstrap using that data. The purpose of this package was to separate out the stages so that researchers could share stratified summary data and fit models to stratified summary data - sadly once that is done it is not possible to bootstrap the CIs in the same way and is a weakness of this method. If you have individual-level data, bootstrapping CI directly to get SEs seems preferable to me.

I put in a bootstrapping option which resamples possible beta values from a normal distribution based on LACE estimates and rebuilds the piecewise-linear model on them, but obviously that has additional assumptions that very much restrict the results and meant they usually looked exactly like using LACE values anyway - suggests of more creative options here would be appreciated.
