### ISSUE TITLE
questions on piecewise_summ_mr and iv_free

### ISSUE THREAD

**Issue by sunyeoplee** [amymariemason/SUMnlmr#29]
1. piecewise_summ_mr function (https://github.com/amymariemason/SUMnlmr/blob/main/R/piecewise_new.R) returns negative standard error when gene-exposure associations have negative coefficients. The line 136, coef_se <- frac_se / xcoef, should be coef_se <- abs(frac_se / xcoef), doesn't it?

2. the iv_free function within the create_nlmr_summary function takes "covar" parameter from inputs of create_nlmr_summary. The "covar" argument in the create_nlmr_summary should specify covariates that need to be included in the first and second stages for 2SLS, I think. However, currently, these covariates are also used to calculate residuals when creating strata. In the line 66-67 
 (https://github.com/amymariemason/SUMnlmr/blob/main/R/nlme_summ_aes.r), residuals are calculated as the observed value subtracted by (intercept, genetic effect, and covariate effects). I thought only the genetic effect should be substracted. I am not sure and would love your guidance. 

Thank you,

Sun.

**Comment by amymariemason** [comment]
1. Oh! Good catch - you can tell my test datasets are all positively aligned! I'll patch this today. 

2. This is a good question that I don't have an immediate answer for. I copied the iv_free from James Staley's nlmr package so that I wouldn't have as much package dependency.  My initial instinct is it shouldn't matter - the only thing we care about is that the residuals are independent of the genetic effect so that which strata someone is grouped into isn't influenced by their genetics and those final strata have different exposure values on average. You are right that I could fit the g+covariate model and then only subtract the genetic effect - it would actually be a simpler piece of code! I will think about whether there could be unintended consequences of this and come back to you!

**Comment by sunyeoplee** [comment]
2. One consequence would be that residuals are harder to interpret. When only the genetic effect is substracted, we can interpret residuals as the expected value of an exposure when the genetic effect is zero. In this case, since genetic effects are often small, the residuals may still be interpretable (please see the following paragraph for another question of mine). When the the covariate (e.g., sex, age, PCs) effects are additionally substracted, the residuals are the expected value of an exposure when the genetic and covariate effects are zero, which are harder to interpret because sometimes the effects of age and sex are large. 

This leads to another question of mine, but this is not regarding the method itself rather than the package, but its related to the consequence of the behavior of the package discussed above.

A paper on the doubly ranked method (https://www.medrxiv.org/content/10.1101/2022.10.26.22280570v2), there is this one statement ("a weakness of the doubly-ranked method is that the strata are not defined with respect to clinically relevant cut-offs of the exposure distribution, and so the interpretation of stratum-specific estimates is less clear"). This suggests that the residual method stratifies based on more clinically relevant criteria. I think this statement is especially true when substracting the small genetic effect rather than large covariate effects in addition to the genetic effect. 

Thanks for your answers!

**Comment by amymariemason** [comment]
This is an interesting point!

I'm mostly visualising models where sex has a clear shift in the values but no other effect - we do want to subtract the effect of sex out before/while considering genetic effects so that we can accurately detect the genetic effects. If we then formed strata only subtracting the genetic effect we could end up with all women at one end, and all men at the other end, whereas if we remove the effect of sex before forming the strata they would be more spread out.  Are there situations where the first case would be desirable? I'd worry about the possibility of confounding via uneven distributions of that covariate across the strata.

The average exposure of each stratum, used in fitting the slope and drawing graph, is calculated on the raw values - so in the sex shift model I'm picturing where the sexes are mixed, it would be an average of the male and female true values, calculated at different levels of the residual.  This is true for both ranked and residual methods.

The issue with the doubly ranked method is that the range of values within each stratum tends to be much wider and have much more overlap, whereas with the residual method true values cluster closers to the average value of the strata. This makes it easier to say the lowest residual is talking about people less than a certain value and the highest residual is talking about people above a certain value. However, differences between the two methods in this regard may be less stark if there are covariates having large effects on the values - we haven't investigated this specifically and would be interested to hear if anyone is finding this. 

In general, we would say to use the ranked method first, assess the constraint exposure assumption and then perhaps apply the residual method to see if it gives more interpretable results.  In this imagined case, we could also fit men and women separately to see whether the curves are truly similar in shape and whether sex is changing the shape of the result.

**Comment by sunyeoplee** [comment]
Thanks for the response. The example on confouding by sex makes sense. Regarding the "clinically relevant subgroups", I was reading this paper (https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-022-02446-6) and was curious how I can interpret the subgroups specified by the authors. For example, HbA1c is grouped as <5.7%, 5.7-6.4%, and >=6.4%. These categories may be clinically relevant in raw values but after substracting the genetic effect, the meaning of these values become less clear. Also, if genetic effects are large, those with large genetic effects may end up in lower residual groups. Can we say these are the people with lower values of exposure in the clinical setting? When a patient comes to a clinic, we only know the observed exposure of that patient, and we don't know her exposure after substracting the genetic effect. 

Maybe all these issues go away because the genetic effects are often small?

Thank you for thinking with me. Your package has been very helpful for my work. Thank you for your work.

**Comment by amymariemason** [comment]
I don't want to comment too much on papers written by other people - you are probably best asking them!
I will note that the instrument was on IL-6 and the subgroups you described are on HbA1c, so I unless there is a lot of correlation between those two biomarkers I wouldn't expect any genetic effect of the instrument on those values.
